### ISSUE TITLE
"typings/global.d.ts" does not exist in npm package

### ISSUE THREAD

**Issue by cboulanger** [retorquere/zotero-sync#2]
Hi, I don't use Typescript, so I am not fully familiar with how it works and could be mistaken. However, you tell npm to include a file "typings/global.d.ts", which does not exist in the source and is not contained in the npm package. Am I missing something?

**Comment by retorquere** [comment]
Thanks for reporting it, 1.0.8 fixes it.

**Comment by cboulanger** [comment]
Thanks for reacting so quickly! I just `npm install  @retorquere/zotero-sync` and updated to 1.0.8. However, I still don't see the typings file in the npm package. I removed everything and reinstalled - still not luck:
 
![Bildschirmfoto 2021-04-17 um 22 33 38](https://user-images.githubusercontent.com/75390/115126096-040cec80-9fcd-11eb-923a-75daf4d291d1.png)

**Comment by retorquere** [comment]
Needed to change the filename in a 2nd place. 1.0.11 is out now.

**Comment by cboulanger** [comment]
Thanks! Just working on a zotero-sync-couchbase Store and learning Typescript along the way. Very useful.

**Comment by retorquere** [comment]
Let me know where it inevitable goes wrong. I still have a fair bit of work to do before I can actually put it to use, but I've tested it and it syncs my own account to json without issue.

**Comment by jonathanschad** [comment]
Hey, I just wanted to play a bit with this library and it seems like for me the changed you made to fix this issue ([Related Commit](https://github.com/retorquere/zotero-sync/commit/cc890810cebbbf5a450232b83fc4b63f083dacff)) broke my typescript. I could not `import { Sync } from "@retorquere/zotero-sync";` without my typescript crashing. 

However if I removed ` "typings": "./typings/zotero.d.ts",` in the package.json the import worked as expected. Im not sure what other sideeffects this has, but I wanted to share the issue.
